from .errors import DataJointError as DataJointError
from _typeshed import Incomplete

class PromiscuousOperand:
    operand: Incomplete
    def __init__(self, operand) -> None: ...

class AndList(list):
    def append(self, restriction) -> None: ...

class Not:
    restriction: Incomplete
    def __init__(self, restriction) -> None: ...

def assert_join_compatibility(expr1, expr2) -> None: ...
def make_condition(query_expression, condition, columns): ...
def extract_column_names(sql_expression): ...
