from _typeshed import Incomplete

class PluginWarning(Exception): ...

class DataJointError(Exception):
    __cause__: Incomplete
    def __init__(self, *args) -> None: ...
    def suggest(self, *args): ...

class LostConnectionError(DataJointError): ...
class QueryError(DataJointError): ...
class QuerySyntaxError(QueryError): ...
class AccessError(QueryError): ...
class MissingTableError(DataJointError): ...
class DuplicateError(QueryError): ...
class IntegrityError(QueryError): ...
class UnknownAttributeError(QueryError): ...
class MissingAttributeError(QueryError): ...
class MissingExternalFile(DataJointError): ...
class BucketInaccessible(DataJointError): ...

ADAPTED_TYPE_SWITCH: str
FILEPATH_FEATURE_SWITCH: str

def _switch_adapted_types(on) -> None: ...
def _support_adapted_types(): ...
def _switch_filepath_types(on) -> None: ...
def _support_filepath_types(): ...
