def key_hash(mapping): ...
def uuid_from_stream(stream, *, init_string: str = ...): ...
def uuid_from_buffer(buffer: bytes = ..., *, init_string: str = ...): ...
def uuid_from_file(filepath, *, init_string: str = ...): ...
