from .errors import DataJointError as DataJointError
from _typeshed import Incomplete
from collections.abc import Generator

class ClassProperty:
    f: Incomplete
    def __init__(self, f) -> None: ...
    def __get__(self, obj, owner): ...

def user_choice(prompt, choices=..., default: Incomplete | None = ...): ...
def get_master(full_table_name: str) -> str: ...
def to_camel_case(s): ...
def from_camel_case(s): ...
def safe_write(filepath, blob) -> None: ...
def safe_copy(src, dest, overwrite: bool = ...) -> None: ...
def parse_sql(filepath) -> Generator[Incomplete, None, None]: ...
